http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 12h

cookie:
  ttl: 12h

grpc:
  port: 4040
  timeout: 5s


userMicroservice:
  host: localhost
  port: 5050


reservationMicroservice:
  host: localhost
  port: 9090


qrMicroservice:
  host: localhost
  port: 7070


notificationMicroservice:
  host: localhost
  port: 6060

